[features]
seeds = false
skip-lint = false
[programs.devnet]
gifportal = "GSU5J6KiUaiZ4AdQmMRepNZf1tegnNPqU6uqh2tQB3tC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/szymon/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
